### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by sqs** [lox/httpcache#7]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with httpcache. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable httpcache on @Sourcegraph by going to https://sourcegraph.com/github.com/lox/httpcache and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by lox** [comment]
Done!
